# Generated by Django 3.2.8 on 2021-10-11 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='culturalEvent_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('manager_image', models.ImageField(blank=True, null=True, upload_to='Upload_Images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='designation_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='document_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employeeType_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eventType_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='holiday_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('alternate_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('DOB', models.DateField()),
                ('address', models.TextField()),
                ('joiningDate', models.DateField()),
                ('qualification', models.TextField()),
                ('experience_year', models.CharField(max_length=10)),
                ('work_experience', models.TextField()),
                ('upload_docs', models.FileField(blank=True, null=True, upload_to='Upload_Images/employeeFiles/')),
                ('upload_docs_2', models.FileField(blank=True, null=True, upload_to='Upload_Images/employeeFiles/')),
                ('upload_docs_3', models.FileField(blank=True, null=True, upload_to='Upload_Images/employeeFiles/')),
                ('upload_docs_4', models.FileField(blank=True, null=True, upload_to='Upload_Images/employeeFiles/')),
                ('upload_docs_5', models.FileField(blank=True, null=True, upload_to='Upload_Images/employeeFiles/')),
                ('profile_image', models.ImageField(upload_to='Upload_Images/profileImages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('designationFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.designation_master', verbose_name='Designation')),
                ('employeeTypeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.employeetype_master', verbose_name='Employee Type')),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserFk')),
            ],
        ),
    ]
