# Generated by Django 3.2.8 on 2021-10-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0003_auto_20211012_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Upload_Images/profileImages/'),
        ),
    ]
