# Generated by Django 3.2.8 on 2021-10-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0004_alter_employeedetails_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='experience_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.experience_master', verbose_name='Experience Year'),
        ),
    ]
