# Generated by Django 3.2.8 on 2021-10-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0006_project_sector_master_project_technology_master_project_type_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_due_date', models.DateField(blank=True, null=True)),
                ('project_overview', models.TextField()),
                ('project_logo', models.ImageField(blank=True, null=True, upload_to='Upload_Images/projectFiles/')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to='Upload_Images/projectFiles/')),
                ('project_status', models.CharField(default='Started', max_length=50)),
                ('project_progress', models.CharField(default='0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('project_manager', models.ManyToManyField(related_name='project_manager', to='taskManagement_App.employeeDetails', verbose_name='project_manager')),
                ('project_sector_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.project_sector_master', verbose_name='project_sector_FK')),
                ('project_team_member', models.ManyToManyField(related_name='project_team_member', to='taskManagement_App.employeeDetails', verbose_name='project_team_member')),
                ('project_technology_fk', models.ManyToManyField(to='taskManagement_App.Project_Technology_Master', verbose_name='project_technology_fk')),
                ('project_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.project_type_master', verbose_name='project_type_fk')),
            ],
        ),
    ]
