# Generated by Django 3.2.8 on 2021-10-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0007_project_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_management',
            name='project_overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
