# Generated by Django 3.2.8 on 2021-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0008_alter_project_management_project_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_management',
            name='project_manager',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_manager', to='taskManagement_App.employeeDetails', verbose_name='project_manager'),
        ),
        migrations.AlterField(
            model_name='project_management',
            name='project_progress',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project_management',
            name='project_status',
            field=models.CharField(blank=True, default='Started', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project_management',
            name='project_team_member',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_team_member', to='taskManagement_App.employeeDetails', verbose_name='project_team_member'),
        ),
    ]
