# Generated by Django 3.2.8 on 2021-10-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0009_auto_20211013_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_management',
            name='project_status',
            field=models.CharField(blank=True, default='Just Started', max_length=50, null=True),
        ),
    ]
