# Generated by Django 3.2.8 on 2021-10-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0010_alter_project_management_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_management',
            name='project_technology_fk',
            field=models.ManyToManyField(blank=True, null=True, to='taskManagement_App.Project_Technology_Master', verbose_name='project_technology_fk'),
        ),
    ]
