# Generated by Django 3.2.8 on 2021-10-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0011_alter_project_management_project_technology_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_management',
            name='project_progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
