# Generated by Django 3.2.8 on 2021-10-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0012_alter_project_management_project_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=100)),
                ('projectFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.project_management', verbose_name='projectFK')),
            ],
            options={
                'unique_together': {('projectFK', 'moduleName')},
            },
        ),
        migrations.CreateModel(
            name='Sub_module_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subModuleName', models.CharField(max_length=100)),
                ('moduleFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.module_management', verbose_name='moduleFK')),
                ('projectFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.project_management', verbose_name='projectFK')),
            ],
            options={
                'unique_together': {('projectFK', 'moduleFK', 'subModuleName')},
            },
        ),
    ]
