# Generated by Django 3.2.8 on 2021-10-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0014_auto_20211013_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_management',
            name='module_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_for',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_for_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_for_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_for_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_url_for_4',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='project_management',
            name='upload_files_1',
            field=models.FileField(blank=True, null=True, upload_to='Upload_Images/projectFiles/'),
        ),
        migrations.AddField(
            model_name='project_management',
            name='upload_files_2',
            field=models.FileField(blank=True, null=True, upload_to='Upload_Images/projectFiles/'),
        ),
        migrations.AddField(
            model_name='project_management',
            name='upload_files_3',
            field=models.FileField(blank=True, null=True, upload_to='Upload_Images/projectFiles/'),
        ),
        migrations.AddField(
            model_name='project_management',
            name='upload_files_4',
            field=models.FileField(blank=True, null=True, upload_to='Upload_Images/projectFiles/'),
        ),
        migrations.AddField(
            model_name='sub_module_management',
            name='subModule_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
