# Generated by Django 3.2.8 on 2021-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0015_auto_20211015_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_management',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_manager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='project_management',
            name='project_team_member',
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_team_member',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='project_management',
            name='project_technology_fk',
        ),
        migrations.AddField(
            model_name='project_management',
            name='project_technology_fk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
