# Generated by Django 3.2.8 on 2021-10-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0017_alter_project_management_project_type_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='designationFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.designation_master', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='employeeTypeFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.employeetype_master', verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='experience_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.experience_master', verbose_name='Experience Year'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
