# Generated by Django 3.2.8 on 2021-10-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0018_auto_20211019_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='joiningDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
