# Generated by Django 3.2.8 on 2021-10-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0019_auto_20211019_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.TextField(unique=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('priority', models.CharField(max_length=10)),
                ('task_status', models.CharField(default='To Do', max_length=10)),
                ('dependencies', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employeeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.employeedetails', verbose_name='employeeFK')),
                ('moduleFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.module_management', verbose_name='moduleFK')),
                ('projectFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.project_management', verbose_name='projectFK')),
                ('submoduleFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.sub_module_management', verbose_name='submoduleFK')),
            ],
        ),
    ]
