# Generated by Django 3.2.8 on 2021-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0020_task_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_management',
            name='created_by',
            field=models.CharField(default='Active', max_length=20),
            preserve_default=False,
        ),
    ]
