# Generated by Django 3.2.8 on 2021-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0021_task_management_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_management',
            name='task_status',
            field=models.CharField(default='To do', max_length=10),
        ),
    ]
