# Generated by Django 3.2.8 on 2021-10-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0024_auto_20211025_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_management',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
