# Generated by Django 3.2.8 on 2021-10-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0026_alter_project_management_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_management',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
