# Generated by Django 3.2.8 on 2021-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0027_alter_task_management_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_management',
            name='delayed_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
