# Generated by Django 3.2.8 on 2021-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0029_rename_delayed_by_task_management_delayed_by_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_management',
            name='reviewed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
