# Generated by Django 3.2.8 on 2021-10-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0030_task_management_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_management',
            name='submoduleFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.sub_module_management', verbose_name='submoduleFK'),
        ),
    ]
