# Generated by Django 3.2.8 on 2021-11-17 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagement_App', '0031_alter_task_management_submodulefk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_management',
            name='task_title',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Notification_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=255)),
                ('notification_type', models.CharField(default='general', max_length=10)),
                ('notification_read_status', models.BooleanField(default=False)),
                ('notification_delete_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('notification_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_created_by', to=settings.AUTH_USER_MODEL, verbose_name='notification_created_by')),
                ('notification_created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_created_for', to=settings.AUTH_USER_MODEL, verbose_name='notification_created_for')),
            ],
        ),
    ]
