# Generated by Django 3.2.8 on 2021-11-17 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagement_App', '0032_auto_20211117_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_management',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification_management',
            name='notification_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_created_by', to=settings.AUTH_USER_MODEL, verbose_name='notification_created_by'),
        ),
        migrations.AlterField(
            model_name='notification_management',
            name='notification_created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_created_for', to=settings.AUTH_USER_MODEL, verbose_name='notification_created_for'),
        ),
        migrations.AlterField(
            model_name='notification_management',
            name='notification_delete_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification_management',
            name='notification_read_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification_management',
            name='notification_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification_management',
            name='notification_type',
            field=models.CharField(blank=True, default='general', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notification_management',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
