# Generated by Django 3.2.8 on 2021-11-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0033_auto_20211117_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_management',
            name='notification_admin_read_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
