# Generated by Django 3.2.8 on 2021-11-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0034_notification_management_notification_admin_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_management',
            name='notification_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
