# Generated by Django 3.2.8 on 2021-11-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0036_notification_management_employee_panel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_management',
            name='notification_linked_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
