# Generated by Django 3.2.8 on 2021-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0039_auto_20211117_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_management',
            name='notification_badge_type',
            field=models.CharField(blank=True, default='<i class="mdi mdi-comment-account-outline text-warning"></i>', max_length=20, null=True),
        ),
    ]
