# Generated by Django 3.2.8 on 2021-11-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0040_alter_notification_management_notification_badge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='alloted_leave',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='remaining_leave',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='taken_leave',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
