# Generated by Django 3.2.8 on 2021-11-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0041_auto_20211118_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date_from', models.DateField(blank=True, null=True)),
                ('leave_date_to', models.DateField(blank=True, null=True)),
                ('leave_reason', models.TextField(blank=True, null=True)),
                ('leave_approval_status', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employeeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.employeedetails', verbose_name='employee_FK')),
            ],
        ),
    ]
