# Generated by Django 3.2.8 on 2021-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0042_leave_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='holiday_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True)),
                ('holiday_date', models.DateField(blank=True, null=True)),
                ('holiday_number', models.CharField(blank=True, max_length=10, null=True)),
                ('holiday_year', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'unique_together': {('holiday_name', 'holiday_date', 'holiday_year', 'holiday_number')},
            },
        ),
    ]
