# Generated by Django 3.2.8 on 2021-11-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0043_holiday_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday_management',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday_management',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
