# Generated by Django 3.2.8 on 2021-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0044_auto_20211119_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday_management',
            old_name='holiday_date',
            new_name='holiday_fromDate',
        ),
        migrations.AddField(
            model_name='holiday_management',
            name='holiday_toDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='holiday_management',
            unique_together={('holiday_name', 'holiday_fromDate', 'holiday_toDate', 'holiday_year', 'holiday_number')},
        ),
    ]
