# Generated by Django 3.2.8 on 2021-11-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0047_auto_20211119_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='send_credentials',
            field=models.CharField(blank=True, default='not-sent', max_length=20, null=True),
        ),
    ]
