# Generated by Django 3.2.8 on 2021-11-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0048_employeedetails_send_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_created_for',
        ),
        migrations.CreateModel(
            name='Notification_reciepents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('notificationFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.notification_management', verbose_name='notificationFK')),
            ],
        ),
    ]
