# Generated by Django 3.2.8 on 2021-11-23 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagement_App', '0049_auto_20211122_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_management',
            name='notification_type',
            field=models.CharField(blank=True, default='single', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='employee_Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserFk')),
            ],
        ),
    ]
