# Generated by Django 3.2.8 on 2021-11-25 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagement_App', '0051_leave_allotment_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_request_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_edit', models.TextField(blank=True, null=True)),
                ('request_status', models.TextField(blank=True, default='pending', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserFk')),
            ],
        ),
    ]
