# Generated by Django 3.2.8 on 2021-11-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0052_employee_request_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_management',
            name='notification_created_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification_reciepents',
            name='send_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
