# Generated by Django 3.2.8 on 2021-11-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0054_auto_20211125_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_bday_annivarsary_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_year', models.CharField(blank=True, max_length=20, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_status', models.CharField(blank=True, default='created', max_length=20, null=True)),
                ('event_highlight', models.CharField(blank=True, max_length=255, null=True)),
                ('event_budget', models.CharField(blank=True, max_length=10, null=True)),
                ('event_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employeeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.employeedetails', verbose_name='employee_FK')),
            ],
        ),
    ]
