# Generated by Django 3.2.8 on 2021-11-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0058_alter_send_bday_anniversary_message_senderfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_bday_annivarsary_management',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event_bday_annivarsary_management',
            name='event_day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event_bday_annivarsary_management',
            name='event_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
