# Generated by Django 3.2.8 on 2021-11-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0059_auto_20211129_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_bday_annivarsary_management',
            name='event_day',
        ),
        migrations.RemoveField(
            model_name='event_bday_annivarsary_management',
            name='event_month',
        ),
        migrations.AddField(
            model_name='event_bday_annivarsary_management',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
