# Generated by Django 3.2.8 on 2021-11-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0061_auto_20211129_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_management',
            name='notification_userCount',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
