# Generated by Django 3.2.8 on 2021-12-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0066_message_archieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='applicationData',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
