# Generated by Django 3.2.8 on 2021-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0069_alter_job_application_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='interviewDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_application',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
