# Generated by Django 3.2.8 on 2021-12-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0070_auto_20211208_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_bday_annivarsary_management',
            name='cultural_eventFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.culturalevent_master', verbose_name='cultural_eventFK'),
        ),
        migrations.AddField(
            model_name='event_bday_annivarsary_management',
            name='cultural_event_creative',
            field=models.FileField(blank=True, null=True, upload_to='Upload_Images/cultural_event_creatives/'),
        ),
        migrations.AddField(
            model_name='event_bday_annivarsary_management',
            name='cultural_event_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event_bday_annivarsary_management',
            name='cultural_event_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event_bday_annivarsary_management',
            name='special_performance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_bday_annivarsary_management',
            name='employeeFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.employeedetails', verbose_name='employee_FK'),
        ),
    ]
