# Generated by Django 3.2.8 on 2021-12-09 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagement_App', '0072_auto_20211208_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('creative', models.FileField(blank=True, null=True, upload_to='Upload_Images/creatives/')),
                ('wish_type', models.CharField(blank=True, default='direct', max_length=50, null=True)),
                ('wish_schedule_time', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('eventFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.event_bday_annivarsary_management', verbose_name='eventFK')),
                ('receiverFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_fk', to='taskManagement_App.employeedetails', verbose_name='employee_FK')),
                ('senderFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_fk', to=settings.AUTH_USER_MODEL, verbose_name='sender_FK')),
            ],
        ),
        migrations.RemoveField(
            model_name='send_bday_anniversary_message',
            name='receiverFK',
        ),
        migrations.RemoveField(
            model_name='send_bday_anniversary_message',
            name='senderFK',
        ),
        migrations.DeleteModel(
            name='scheduler_message',
        ),
        migrations.DeleteModel(
            name='send_bday_anniversary_message',
        ),
    ]
