# Generated by Django 3.2.8 on 2021-12-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0073_auto_20211209_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_wishes',
            name='wish_status',
            field=models.CharField(blank=True, default='sent', max_length=20, null=True),
        ),
    ]
