# Generated by Django 3.2.8 on 2021-12-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0075_location_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
