# Generated by Django 3.2.8 on 2021-12-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0077_secretkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_management',
            name='edit_leave_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leave_allotment_management',
            name='leave_reason',
            field=models.TextField(blank=True, default='Monthly Paid Leave', null=True),
        ),
    ]
