# Generated by Django 3.2.8 on 2021-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0078_auto_20211217_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_management',
            name='edit_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave_management',
            name='edit_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
