# Generated by Django 3.2.8 on 2021-12-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0079_auto_20211218_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_management',
            name='request_edit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
