# Generated by Django 3.2.8 on 2021-12-18 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagement_App', '0080_leave_management_request_edit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_admin_read_status',
        ),
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_creatives',
        ),
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_delete_status',
        ),
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_description',
        ),
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_read_status',
        ),
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_sender',
        ),
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_title',
        ),
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification_management',
            name='notification_userCount',
        ),
        migrations.AddField(
            model_name='notification_management',
            name='member_count',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='notification_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='notification_location',
            field=models.CharField(blank=True, default='inbox', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='notification_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='notification_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='notification_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification_reciepents',
        ),
    ]
