# Generated by Django 3.2.8 on 2021-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0081_auto_20211218_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
