# Generated by Django 3.2.8 on 2021-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0082_employeedetails_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_management',
            old_name='read_status',
            new_name='admin_read_status',
        ),
        migrations.AddField(
            model_name='notification_management',
            name='admin_trash_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='emp_read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='emp_trash_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='manager_read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='manager_trash_status',
            field=models.BooleanField(default=False),
        ),
    ]
