# Generated by Django 3.2.8 on 2021-12-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0083_auto_20211221_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_management',
            name='admin_starred_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='emp_starred_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_management',
            name='manager_starred_status',
            field=models.BooleanField(default=False),
        ),
    ]
