# Generated by Django 3.2.8 on 2021-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0084_auto_20211221_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_management',
            name='project_status_force_update',
            field=models.CharField(blank=True, default='In Progress', max_length=50, null=True),
        ),
    ]
