# Generated by Django 3.2.8 on 2021-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0086_file_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_management',
            name='project_to_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
