# Generated by Django 3.2.8 on 2022-01-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement_App', '0087_project_management_project_to_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_management',
            name='projectFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagement_App.project_management'),
        ),
    ]
